<?
session_start();
require_once("validador.php");
require_once("productos.php");
require_once("usuario.php");
require_once("tarjetas.php");
require_once("metodoPago.php");
require_once("carritoClase.php");
require_once("registroClase.php");
require_once("loginClase.php");
require_once("baseDatos.php");
