<?php
session_start();
require_once("ValidadorLogin.php");
require_once("productos.php");
require_once("usuario.php");
require_once("tarjeta.php");
require_once("metodoPago.php");
require_once("carritoClase.php");
require_once("registroClase.php");
require_once("loginClase.php");
require_once("baseDatos.php");
